# Load Balancer: Shop Information Service

upstream shop-service {
    server shop-service:3001;
    # server shop-service-2:3001;
}

server {
    listen 80;
    server_name _;

    location / {
        proxy_pass         http://shop-service;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   Cookie            $http_cookie;
        proxy_read_timeout 60s;
    }
}
